Repository ArmaAchilles/Achilles, pull requests merged in 2018-04, with the labels that each got.

#286 German and French Translations
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
Labels: change, priority/medium

#247 Changes to Suppressive Fire #241:
  @AresModAchillesExpansion/addons/functions_f_achilles/cfgFunctions.hpp
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_createDummyLogic.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_forceWeaponFire.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_getLogics.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_getWeaponsMuzzlesMagazines.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_logicSelector.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_positionSelector.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_SuppressiveFire.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_getWeaponsMuzzlesMagazines.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/replacement/fn_curatorObjectEdited.sqf
  @AresModAchillesExpansion/addons/functions_f_ares/common/fn_GetFarthest.sqf
  @AresModAchillesExpansion/addons/functions_f_ares/common/fn_GetNearest.sqf
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/addons/modules_f_achilles/FireSupport/cfgVehiclesModulesFireSupport.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/FireSupport/functions/fn_ModuleFireSupportSuppressiveFire.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/Objects/functions/fn_ObjectsAttachTo.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/Reinforcements/functions/fn_ReinforcementsSupplyDrop.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/Reinforcements/functions/fn_ReinforcementsCreateUnits.sqf
  @AresModAchillesExpansion/addons/ui_f/functions/keyEvents/fn_HandleCuratorObjectDeleted.sqf
Labels: change, fix, priority/low

#287 Naked and transfer ownership
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_SuppressiveFire.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/FireSupport/functions/fn_ModuleFireSupportSuppressiveFire.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/Objects/functions/fn_ObjectsTransferOwnership.sqf
Labels: bug, priority/low

#288 Fix Arsenal Modules
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_updateStandardInventory.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/Arsenal/functions/fn_ArsenalAddFull.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/Arsenal/functions/fn_ArsenalRemove.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/Arsenal/cfgFunctionsArsenal.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/Arsenal/cfgVehiclesModulesArsenal.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/Arsenal/functions/fn_ArsenalAddCustom.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/Arsenal/functions/fn_ArsenalAddFull.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/Arsenal/functions/fn_ArsenalCopyToClipboard.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/Arsenal/functions/fn_ArsenalCreateAaf.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/Arsenal/functions/fn_ArsenalCreateCsat.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/Arsenal/functions/fn_ArsenalCreateGuerilla.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/Arsenal/functions/fn_ArsenalCreateNato.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/Arsenal/functions/fn_ArsenalPasteCombine.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/Arsenal/functions/fn_ArsenalPasteReplace.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/cfgFunctions.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/cfgVehiclesModuleBase.hpp
Labels: bug, priority/medium

#289 Change Add-On Name to Achilles
  .github/ISSUE_TEMPLATE.md
  @AresModAchillesExpansion/LICENSE
  @AresModAchillesExpansion/addons/functions_f_achilles/cfgFunctions.hpp
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/addons/settings_f/scripts/keybindings.sqf
  @AresModAchillesExpansion/addons/ui_f/cfgMods.hpp
  @AresModAchillesExpansion/addons/ui_f/functions/eventHandler/fn_onDisplayCuratorLoad.sqf
  @AresModAchillesExpansion/changelog.md
  @AresModAchillesExpansion/credits.md
  @AresModAchillesExpansion/mod.cpp
  LICENSE
  README.md
Labels: change, priority/low

#290 Additions in the Wake of the Tank DLC
  @AresModAchillesExpansion/addons/functions_f_achilles/cfgFunctions.hpp
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/changeAttributes/fn_setSensors.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_changeAccessoires.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_setFlag.sqf
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/addons/modules_f_achilles/FireSupport/functions/fn_ModuleFireSupportCreateUniversalTarget.sqf
  @AresModAchillesExpansion/addons/ui_f/dialogs/Replacement/RscDisplayAttributesMan.hpp
  @AresModAchillesExpansion/addons/ui_f/dialogs/Replacement/RscDisplayAttributesVehicle.hpp
  @AresModAchillesExpansion/changelog.md
Labels: change, feature, fix, priority/medium

#293 Small fixes
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/addons/modules_f_achilles/Buildings/functions/fn_BuildingsDestroy.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/Replacement/cfgVehiclesModulesReplacement.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/Spawn/cfgVehiclesModulesSpawn.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/Spawn/functions/fn_SpawnCarrier.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/Spawn/cfgVehiclesModulesSpawn.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/Zeus/cfgVehiclesModulesZeus.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/Zeus/functions/fn_ZeusHint.sqf
  @AresModAchillesExpansion/addons/ui_f/dialogs/RscDialogCopyPaste.hpp
Labels: fix, priority/low

#294 Hint module is now shown as Advanced Hint
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/addons/modules_f_achilles/cfgVehiclesModuleBase.hpp
Labels: change, priority/low
