Repository ArmaAchilles/Achilles, pull requests merged in 2018-10, with the labels that each got.

#392 Fixed Ambient Animation typo
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_animation.sqf
Labels: fix, priority/lowest, testing/not tested

#387 Fix Limited Arsenal
  @AresModAchillesExpansion/addons/modules_f_achilles/Arsenal/functions/fn_ArsenalCreateCustom.sqf
Labels: fix, priority/high

#384 Do not kill curators and logics
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/selectUnit/fn_switchUnit_exit.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/selectUnit/fn_switchUnit_start.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/FireSupport/functions/fn_ModuleFireSupportNuke.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/Objects/functions/fn_ModuleObjectsMakeInvincible.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/Zeus/functions/fn_ZeusVisibility.sqf
Labels: fix, priority/medium, testing/tested
