Repository ArmaAchilles/Achilles, pull requests merged in 2018-08, with the labels that each got.

#345 Revise README
  README.md
Labels: change, documentation, priority/high

#350 Revert "Updated release branch (#334) (#349)"
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/addons/modules_f_ares/Reinforcements/functions/fn_ReinforcementsCreateUnits.sqf
Labels: change, priority/high

#348 Updated French Translation.
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
Labels: change, priority/medium

#353 Update GitBash.md
  tools/cheatsheets/GitBash.md
Labels: change, priority/low
