Repository ArmaAchilles/Achilles, pull requests merged in 2018-07, with the labels that each got.

#329 Add Traditional Chinese Translation
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
Labels: feature, priority/medium

#336 Get dialogs working for any resolution
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/AchillesDynamicDialog.h
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_ShowChooseDialog.sqf
  @AresModAchillesExpansion/addons/ui_f/dialogs/RscBaseClasses.hpp
  @AresModAchillesExpansion/addons/ui_f/dialogs/RscDialogCompositions.hpp
  @AresModAchillesExpansion/addons/ui_f/dialogs/RscDialogCopyPaste.hpp
  @AresModAchillesExpansion/addons/ui_f/dialogs/RscDialogDynamic.hpp
  @AresModAchillesExpansion/addons/ui_f/dialogs/RscDialogExecuteCode.hpp
  @AresModAchillesExpansion/addons/ui_f/functions/dynamic/fn_ShowChooseDialog.sqf
  @AresModAchillesExpansion/addons/ui_f/scripts/RscDisplayAttributes.sqf
Labels: fix, priority/high

#337 Fix unexpected teleportation of switched units
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/selectUnit/fn_switchUnit_start.sqf
Labels: fix, priority/low

#339 Faction filter and reinforcement compatibility
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/addons/modules_f_achilles/Reinforcements/functions/fn_ReinforcementsSupplyDrop.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/Reinforcements/functions/fn_ReinforcementsCreateUnits.sqf
  @AresModAchillesExpansion/addons/settings_f/scripts/available_factions.sqf
  @AresModAchillesExpansion/addons/ui_f/functions/dialogs/fn_RscDisplayAttributes_CreateReinforcement.sqf
  @AresModAchillesExpansion/addons/ui_f/functions/dialogs/fn_RscDisplayAttributes_SupplyDrop.sqf
  @AresModAchillesExpansion/addons/ui_f/functions/eventHandler/fn_onModuleTreeLoad.sqf
Labels: fix, priority/medium

#340 Resize GUI grids in order to keep text grids fixed
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/AchillesDynamicDialog.h
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_ShowChooseDialog.sqf
  @AresModAchillesExpansion/addons/ui_f/dialogs/Replacement/RscDisplayAttributesModuleTree.hpp
  @AresModAchillesExpansion/addons/ui_f/dialogs/RscBaseClasses.hpp
  @AresModAchillesExpansion/addons/ui_f/dialogs/RscDialogCompositions.hpp
  @AresModAchillesExpansion/addons/ui_f/dialogs/RscDialogCopyPaste.hpp
  @AresModAchillesExpansion/addons/ui_f/dialogs/RscDialogDynamic.hpp
  @AresModAchillesExpansion/addons/ui_f/dialogs/RscDialogExecuteCode.hpp
  @AresModAchillesExpansion/addons/ui_f/functions/dynamic/fn_ShowChooseDialog.sqf
Labels: change, priority/low

#341 Get missing groups as reinforcement
  @AresModAchillesExpansion/addons/modules_f_ares/Reinforcements/functions/fn_ReinforcementsCreateUnits.sqf
Labels: fix, priority/medium

#343 Add 1.1.1 change log
  @AresModAchillesExpansion/changelog.md
  @AresModAchillesExpansion/credits.md
Labels: change, priority/medium
