Repository ArmaAchilles/Achilles, pull requests merged in 2018-03, with the labels that each got.

#266 Japanese translation
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
Labels: feature, priority/low

#274 Remote Execs to Call and fix #248
  @AresModAchillesExpansion/addons/modules_f_ares/Zeus/functions/fn_ZeusVisibility.sqf
Labels: fix, priority/medium

#271 Added universal target #270
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/addons/modules_f_achilles/FireSupport/cfgFunctionsFireSupport.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/FireSupport/cfgVehiclesModulesFireSupport.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/FireSupport/functions/fn_ModuleFireSupportCAS.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/FireSupport/functions/fn_ModuleFireSupportCreateCASTarget.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/FireSupport/functions/fn_ModuleFireSupportCreateSuppressionTarget.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/FireSupport/functions/fn_ModuleFireSupportCreateUniversalTarget.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/FireSupport/functions/fn_ModuleFireSupportSuppressiveFire.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/config.cpp
  @AresModAchillesExpansion/addons/modules_f_ares/FireSupport/cfgFunctionsFireSupport.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/FireSupport/cfgVehiclesModulesFireSupport.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/FireSupport/functions/fn_FireSupportArtilleryFireMission.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/FireSupport/functions/fn_FireSupportCreateArtilleryTarget.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/config.cpp
Labels: change, feature, priority/low

#276 Correct Change Side Relations Radio Message
  @AresModAchillesExpansion/addons/modules_f_achilles/MissionFlow/functions/fn_changeSideRelations.sqf
Labels: fix, priority/low

#278 Fix Rotation of Basic CAS Modules
  @AresModAchillesExpansion/addons/ui_f/functions/keyEvents/fn_HandleCuratorObjectEdited.sqf
Labels: fix, priority/high

#277 Equipment: Set Flag, Attach Effect and Renaming
  @AresModAchillesExpansion/addons/functions_f_achilles/cfgFunctions.hpp
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_ShowChooseDialog.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_setFlag.sqf
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/addons/modules_f_achilles/Equipment/cfgFunctionsEquipment.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/Equipment/cfgVehiclesModulesEquipment.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/Equipment/functions/fn_attachDetachEffect.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/cfgFunctions.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/cfgVehiclesModuleBase.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/config.cpp
  @AresModAchillesExpansion/addons/modules_f_ares/Equipment/cfgVehiclesModulesEquipment.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/Equipment/functions/fn_EquipmentFlashlightIRLaserOnOff.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/Equipment/functions/fn_EquipmentNVDRailAttachment.sqf
  @AresModAchillesExpansion/addons/ui_f/dialogs/Replacement/RscDisplayAttributesMan.hpp
  @AresModAchillesExpansion/addons/ui_f/dialogs/Replacement/RscDisplayAttributesVehicle.hpp
Labels: feature, priority/low

#282 Localization for Chinese Simplified
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
Labels: feature, priority/medium

#283 Fix in Achilles_fnc_spawn for Persistent Smoke Pillar
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_spawn.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_spawn_remote.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/Effects/functions/fn_lightSourceAttributes.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/Effects/functions/fn_moduleLightSource.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/Effects/functions/fn_spawnSmoke.sqf
Labels: fix, priority/medium

#285 Arsenal Modules: Enable Vanilla Arsenal with ACE and Reintroduce Copy/Paste of Standard Inventory
  @AresModAchillesExpansion/addons/functions_f_achilles/cfgFunctions.hpp
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_updateStandardInventory.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_updateVirtualArsenal.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_ArsenalSetup.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_ArsenalSetupACE.sqf
  @AresModAchillesExpansion/addons/functions_f_ares/cfgFunctions.hpp
  @AresModAchillesExpansion/addons/functions_f_ares/features/fn_ArsenalSetup.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/Arsenal/functions/fn_ArsenalCopyToClipboard.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/Arsenal/functions/fn_ArsenalPaste.sqf
Labels: change, priority/high
