Repository ArmaAchilles/Achilles, pull requests merged in 2018-09, with the labels that each got.

#363 Update Japanese translation
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
Labels: change, priority/low

#368 Replace linalg and statistics utilities with CBA and BIS functions
  @AresModAchillesExpansion/addons/functions_f_achilles/cfgFunctions.hpp
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_arrayMean.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_getUnitAmmoDef.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_getVehicleAmmoDef.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_matrixTranspose.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_vectorMap.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_groupObjects.sqf
  @AresModAchillesExpansion/addons/ui_f/functions/keyEvents/fn_HandleCuratorObjectEdited.sqf
Labels: change, priority/medium

#371 Use correct spawn position right from the beginning
  @AresModAchillesExpansion/addons/modules_f_achilles/Spawn/functions/fn_SpawnAdvancedCompositions.sqf
Labels: fix, priority/medium

#369 Fix exception handling and add support LWIRCM from RHS
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_LaunchCM.sqf
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
Labels: fix, priority/medium

#365 Handle VLS
  @AresModAchillesExpansion/addons/modules_f_ares/FireSupport/functions/fn_FireSupportArtilleryFireMission.sqf
Labels: feature, priority/medium

#362 Added toggle include crew keybind
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/addons/settings_f/scripts/keybindings.sqf
  @AresModAchillesExpansion/addons/ui_f/functions/keyEvents/fn_HandleCuratorObjectPlaced.sqf
Labels: feature, priority/low, testing/tested

#372 Add Module Filter
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/init/fn_onCuratorStart.sqf
  @AresModAchillesExpansion/addons/functions_f_ares/common/fn_RegisterCustomModule.sqf
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/addons/modules_f_achilles/ACE/cfgVehiclesModulesACE.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/Arsenal/cfgVehiclesModulesArsenal.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/Behaviours/cfgVehiclesModulesBehaviours.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/Buildings/cfgVehiclesModulesBuildings.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/DevTools/cfgVehiclesModulesDevTools.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/Environment/cfgVehiclesModulesEnvironment.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/Equipment/cfgVehiclesModulesEquipment.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/FireSupport/cfgVehiclesModulesFireSupport.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/MissionFlow/cfgVehiclesModulesMissionFlow.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/Objects/cfgVehiclesModulesObjects.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/Player/cfgVehiclesModulesPlayer.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/Reinforcements/cfgVehiclesModulesReinforcements.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/Replacement/cfgVehiclesModulesReplacement.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/Spawn/cfgVehiclesModulesSpawn.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/Zeus/cfgVehiclesModulesZeus.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/Behaviours/cfgVehiclesModulesBehaviours.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/Custom/cfgVehiclesModulesUserDefined.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/DevTools/cfgVehiclesModulesDevTools.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/Equipment/cfgVehiclesModulesEquipment.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/FireSupport/cfgVehiclesModulesFireSupport.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/Player/cfgVehiclesModulesPlayer.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/Reinforcements/cfgVehiclesModulesReinforcements.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/Spawn/cfgVehiclesModulesSpawn.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/Zeus/cfgVehiclesModulesZeus.hpp
  @AresModAchillesExpansion/addons/settings_f/scripts/XEH_preInit.sqf
  @AresModAchillesExpansion/addons/settings_f/scripts/available_factions.sqf
  @AresModAchillesExpansion/addons/settings_f/scripts/available_modules.sqf
  @AresModAchillesExpansion/addons/ui_f/functions/eventHandler/fn_AppendToModuleTree.sqf
  @AresModAchillesExpansion/addons/ui_f/functions/eventHandler/fn_onDisplayCuratorLoad.sqf
  @AresModAchillesExpansion/addons/ui_f/functions/eventHandler/fn_onModuleTreeLoad.sqf
Labels: change, feature, fix, priority/medium, testing/tested

#370 Surprise
  @AresModAchillesExpansion/addons/data_f_achilles/icons/icon_nuclear.paa
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/addons/modules_f_achilles/FireSupport/cfgFunctionsFireSupport.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/FireSupport/cfgVehiclesModulesFireSupport.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/FireSupport/functions/fn_ModuleFireSupportNuke.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/config.cpp
  @AresModAchillesExpansion/credits.md
Labels: feature, priority/medium, testing/tested

#373 Update to 1.2.0
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/changelog.md
  @AresModAchillesExpansion/credits.md
  @AresModAchillesExpansion/mod.cpp
Labels: change, priority/medium

#374 Fix Nuke
  @AresModAchillesExpansion/addons/modules_f_achilles/FireSupport/cfgVehiclesModulesFireSupport.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/FireSupport/functions/fn_ModuleFireSupportNuke.sqf
Labels: fix, priority/high, testing/tested
