Repository ArmaAchilles/Achilles, pull requests merged in 2018-06, with the labels that each got.

#317 Added DeliciousJaffa
  @AresModAchillesExpansion/credits.md
Labels: fix, priority/high

#320 Create Mission SQF: Replace nonsensical default value
  @AresModAchillesExpansion/addons/modules_f_ares/DevTools/functions/fn_CreateMissionSQF.sqf
Labels: fix, priority/low

#321 Small features
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_chute.sqf
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/addons/modules_f_ares/FireSupport/functions/fn_FireSupportArtilleryFireMission.sqf
Labels: change, feature, priority/low

#323 Reorganize Tools
  .gitignore
  .travis.yml
  Tools/AddonBuilder.bat
  Tools/find_unsafe_rc.sh
  Tools/git-bash.bat
  Tools/markdown_changeLog_to_steam.py
  Tools/markdown_test.txt
  Tools/markdown_test_steam.txt
  Tools/unsafe_rc.log
  tools/AchillesAddonBuilder.bat.example
  tools/AchillesConnectToServer.bat.example
  tools/cheatsheets/GitBash.md
  tools/cheatsheets/util_command_lines.sh
  tools/fixes/SqfVisibilityFixer.groovy
  tools/fixes/edit_custom_module_script.py
  tools/fixes/list_unsafe_remote_exec.log
  tools/fixes/list_unsafe_remote_exec.sh
  tools/start-mintty.bat
  tools/travis/config_style_checker.py
  tools/travis/sqf_validator.py
  tools/updateRemoteExecWhiteList.sh
Labels: change, priority/low

#326 Reintroduce the faction filter
  @AresModAchillesExpansion/addons/settings_f/scripts/XEH_preInit.sqf
  @AresModAchillesExpansion/addons/ui_f/functions/eventHandler/fn_onModuleTreeLoad.sqf
  @AresModAchillesExpansion/changelog.md
Labels: change, priority/low

#324 HALO
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_chute.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/scripts/fn_wpParadrop.sqf
  @AresModAchillesExpansion/addons/functions_f_ares/features/fn_TeleportPlayers.sqf
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/addons/modules_f_ares/Player/functions/fn_PlayerTeleport.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/Reinforcements/functions/fn_ReinforcementsCreateUnits.sqf
  @AresModAchillesExpansion/addons/ui_f/functions/dialogs/fn_RscDisplayAttributes_CreateReinforcement.sqf
  @AresModAchillesExpansion/changelog.md
Labels: feature, priority/medium

#327 Change 1.0.3 to 1.1.0
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/changelog.md
  @AresModAchillesExpansion/mod.cpp
Labels: change, priority/low

#328 Fix locality issue for HALO option in the teleport module
  @AresModAchillesExpansion/addons/functions_f_ares/features/fn_TeleportPlayers.sqf
Labels: fix, priority/medium
