Repository ArmaAchilles/Achilles, pull requests merged in 2019-01, with the labels that each got.

#432 Update ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: change, priority/low

#434 Prefix switch unit config entry for ACE Zeus actions
  .gitignore
  @AresModAchillesExpansion/addons/ui_f/ACE_ZeusActions.hpp
Labels: change, priority/low, testing/tested

#424 Optimize dir pitch bank utilities
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_getDirPitchBank.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_vectDirUpFromDirPitchBank.sqf
Labels: change, fix, priority/medium, testing/tested

#438 Set up CI with Azure Pipelines
  azure-pipelines.yml
Labels: change, feature, priority/medium, testing/tested

#439 Rewrote and added Select Units to Patrol module (no conflicts)
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/addons/modules_f_achilles/Behaviours/cfgFunctionsBehaviours.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/Behaviours/cfgVehiclesModulesBehaviours.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/Behaviours/functions/fn_BehaviourPatrol.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/config.cpp
  @AresModAchillesExpansion/addons/modules_f_ares/Behaviours/cfgFunctionsBehaviours.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/Behaviours/cfgVehiclesModulesBehaviours.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/Behaviours/functions/fn_BehaviourPatrol.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/config.cpp
Labels: change, feature, priority/low, testing/tested

#443 Added some Russian translations
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
Labels: change, feature, priority/medium

#442 Replaced Travis badge with Pipelines one
  README.md
Labels: change, priority/low, testing/tested

#445 Add Spanish translation for pretty much all the strings
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
Labels: feature, priority/medium

#448 Fix Spanish translation merging
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
Labels: fix, priority/high

#447 Added hotkey for chatter module
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_chatter.sqf
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/addons/settings_f/scripts/keybindings.sqf
Labels: feature, priority/low, testing/tested

#435 Fix various misspellings
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_arrayStdDev.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_getDirPitchBank.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_transferOwnership.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_vectAngleXY.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_PreplaceMode.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_advancedBlackfishCAS.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_advancedHeliCAS.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_advancedPlaneCAS.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/interpolation/fn_interpolation_cubicBezier1D.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/interpolation/fn_interpolation_cubicBezier1D_slope.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/selectUnit/fn_switchUnit_exit.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/selectUnit/fn_switchUnit_start.sqf
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/addons/ui_f/functions/common/fn_SelectUnits.sqf
  @AresModAchillesExpansion/changelog.md
  @AresModAchillesExpansion/credits.md
  README.md
Labels: fix, priority/low
