Repository ArmaAchilles/Achilles, pull requests merged in 2019-06, with the labels that each got.

#488 Fixed inventory attribute after latest Arma update
  @AresModAchillesExpansion/addons/ui_f/scripts/RscAttributeInventory.sqf
Labels: feature, fix, priority/high, testing/tested

#493 Added Detailed Installation Guide
  azure-pipelines.yml
  docs/source/intro/installing-achilles-images/1.png
  docs/source/intro/installing-achilles-images/2.png
  docs/source/intro/installing-achilles-images/3.png
  docs/source/intro/installing-achilles-images/4.png
  docs/source/intro/installing-achilles-images/5.png
  docs/source/intro/installing-achilles-images/6.png
  docs/source/intro/installing-achilles.rst
Labels: documentation, testing/tested

#497 Add game logic to side control as a secondary control
  addons/dialog/dynamicDialog.hpp
  addons/dialog/functions/fnc_create.sqf
  addons/dialog/functions/fnc_dynamic_sides.sqf
  addons/dialog/script_idc.hpp
  docs/source/features/dynamic-dialog.rst
Labels: change, documentation, fix, priority/medium, testing/tested

#502 Add description block control to dynamic dialog
  addons/dialog/XEH_PREP.hpp
  addons/dialog/dynamicDialog.hpp
  addons/dialog/functions/fnc_create.sqf
  addons/dialog/functions/fnc_dynamic_description.sqf
  addons/dialog/script_idc.hpp
  docs/source/features/dynamic-dialog-images/12.png
  docs/source/features/dynamic-dialog.rst
Labels: documentation, feature, priority/medium, testing/tested

#504 Add resource function to control elements
  addons/dialog/functions/fnc_create.sqf
  docs/source/features/dynamic-dialog.rst
Labels: feature, priority/medium, testing/tested
