Repository ArmaAchilles/Achilles, pull requests merged in 2019-02, with the labels that each got.

#451 Update fn_ModuleACEHeal.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/ACE/functions/fn_ModuleACEHeal.sqf
Labels: fix, priority/medium, testing/tested

#457 Parachutes don't spawn for disabled simulation objects
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/replacement/fn_curatorObjectEdited.sqf
Labels: fix, priority/medium, testing/tested

#458 Fix Hint Module inheritance
  @AresModAchillesExpansion/addons/modules_f_achilles/Zeus/cfgVehiclesModulesZeus.hpp
Labels: change, priority/low, testing/tested

#455 Rework inventory attribute
  @AresModAchillesExpansion/addons/ui_f/scripts/RscAttributeInventory.sqf
Labels: change, priority/low, testing/tested

#459 Revert "Fix Hint Module inheritance"
  @AresModAchillesExpansion/addons/modules_f_achilles/Zeus/cfgVehiclesModulesZeus.hpp
Labels: fix, priority/high
