Repository ArmaAchilles/Achilles, pull requests merged in 2019-03, with the labels that each got.

#437 Add option to disable transition effects for the damage building module
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_damageBuildings.sqf
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/addons/modules_f_achilles/Buildings/functions/fn_BuildingsDestroy.sqf
Labels: feature, priority/low, testing/not tested, testing/tested

#467 Fixed flag accessory not working for double quotes
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_changeAccessoires.sqf
Labels: fix, priority/medium, testing/tested

#475 Remove Travis CI from Achilles
  .travis.yml
Labels: change, priority/low
