Repository ArmaAchilles/Achilles, pull requests merged in 2019-09, with the labels that each got.

#485 Adds More Animations
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_ambientAnimGetParams.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_animation.sqf
Labels: change, feature, priority/low, testing/tested

#483 Sort music alphabetically and resume last track on re-open
  @AresModAchillesExpansion/addons/ui_f/scripts/RscAttributeMusic.sqf
Labels: change, feature, priority/low, testing/tested

#453 Rework ammo attribute
  @AresModAchillesExpansion/addons/functions_f_achilles/cfgFunctions.hpp
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_getAllTurrets.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_getVehicleAmmo.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_getVehicleAmmoDef.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_setMagazineAmmo.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_setTurretAmmo.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_setVehicleAmmo.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/common/fn_setVehicleAmmoDef.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/FireSupport/functions/fn_ModuleFireSupportSuppressiveFire.sqf
  @AresModAchillesExpansion/addons/ui_f/scripts/RscAttributeAmmo.sqf
Labels: change, priority/medium, testing/not tested

#489 Fixed wrong hyperlinks in the table of contents
  README.md
Labels: fix, priority/low, testing/tested

#466 Rewrote surrender modules
  @AresModAchillesExpansion/addons/functions_f_achilles/cfgFunctions.hpp
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/changeAttributes/fn_changeSide_local.sqf
  @AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_surrenderUnit.sqf
  @AresModAchillesExpansion/addons/functions_f_ares/cfgFunctions.hpp
  @AresModAchillesExpansion/addons/functions_f_ares/features/fn_surrenderUnit.sqf
  @AresModAchillesExpansion/addons/language_f/stringtable.xml
  @AresModAchillesExpansion/addons/modules_f_achilles/Behaviours/cfgFunctionsBehaviours.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/Behaviours/cfgVehiclesModulesBehaviours.hpp
  @AresModAchillesExpansion/addons/modules_f_achilles/Behaviours/functions/fn_BehaviourSurrenderUnits.sqf
  @AresModAchillesExpansion/addons/modules_f_achilles/config.cpp
  @AresModAchillesExpansion/addons/modules_f_ares/Behaviours/cfgFunctionsBehaviours.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/Behaviours/cfgVehiclesModulesBehaviours.hpp
  @AresModAchillesExpansion/addons/modules_f_ares/Behaviours/functions/fn_BehaviourSurrenderUnits.sqf
  @AresModAchillesExpansion/addons/modules_f_ares/config.cpp
Labels: change, feature, priority/low, testing/not tested
